apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base-config

patches:
- path: infra-base-modsec-conf-confmap.yaml
  target:
    kind: ConfigMap
    name: modsecurity-configmap-modsecurity-conf
    namespace: networking-engineering-dockerized-nvf-project
- path: infra-base-modsec-customrules-confmap.yaml
  target:
    kind: ConfigMap
    name: modsecurity-configmap-rules
    namespace: networking-engineering-dockerized-nvf-project

